apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-todo
  labels:
    app: api-todo
spec:
  selector:
    matchLabels:
      app: api-todo
  template:
    metadata:
      labels:
        app: api-todo
    spec:
      containers:
      - name: backend
        image: sv301185/api-todo
        ports:
        - containerPort: 3003
        env:
        - name: MONGO_URL
          value: "mongodb"
        - name: API_PORT
          value: "3003"

---
apiVersion: v1
kind: Service
metadata:
  name: api-todo
  labels:
     app: api-todo
spec:
  # type: NodePort
  selector:
    app: api-todo
  ports:
    - port      : 3003
      targetPort: 3003
      # nodePort: 30003

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: api-todo-ha
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: api-todo
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80
