apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    app: todo
spec:
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: mongodb-container
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
          - name: db
            mountPath: /data/db
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: myclaim

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: todo
spec:
  ports:
    - port: 27017
  selector:
    app: todo

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath
