---
# tasks file for deploy_traefik_consul_vault

- name: Generate Docker-compose file
  template: src=docker-compose.j2 dest={{ destin_folder }}/docker-compose.yml

- name: Create Folder configuration
  file:
    path: /home/vagrant/configuration
    state: directory
    mode: 0755

# Task for creating selfsigned sertification for my domain
- name: Create certificate
  copy: src=create_certificate_for_domain.sh dest=/home/vagrant/configuration/ mode=755
- name: Generate certeficate
  shell: ./configuration/create_certificate_for_domain.sh First-node.my.domain
- name: Create certificate
  copy: src=certificates.yml dest=/home/vagrant/configuration/

# Create cron job for revoke certificate if it needed
- name: Create cron job for revoke certeficate
  cron:
    name: "create_certificate"
    hour: "8"
    job: "/home/vagrant/configuration/create_certificate_for_domain.sh First-node.my.domain"

- name: Start traefik_consul_vault
  shell: docker-compose up -d
