---
# tasks file for jenkins_master
# - block: # =======Block for BCP======
#    - name: Copying the file
#      fetch:
#        src: /mnt/sdb/bcp/jmaster/{{bcname}}
#        dest: /tmp/
#        flat: yes
#  when: inventory_hostname == "bcp"
    
- block: # =======Block for MASTER======

    - name: DNS
      copy: src=/home/silver/ansible/files/resolv.conf dest=/etc/

    - name: Install yum GIT JAVA WGET
      yum:
        name:
          - wget
          - nano
          - java-1.8.0-openjdk
          - git

    - name: Download jenkins.repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins Key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start & Enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: true

    - name: Open Firewall Port
      firewalld:
        zone: public
        port: 8080/tcp
        permanent: true
        state: enabled
        immediate: true

#    - name: Wait
#      wait_for: timeout=30

#    - name: Restore
#      copy: src=/tmp/{{bcname}} dest=/tmp/ 
    
    - name: Sopped Jenkins
      systemd:
        name: jenkins
        state: stopped    

    - name: Copy the file from bcp to master
      tags: sync-push
      synchronize:
        src: /mnt/sdb/bcp/jmaster/{{bcname}}
        dest: /tmp/{{bcname}}
        mode: push
      delegate_to: "{{groups['jenkins'][2]}}"
      register: syncfile            

    - name: Restore Jenkins on Master Node
      ansible.builtin.unarchive:
        src: /tmp/{{bcname}}
        dest: /
        remote_src: yes
        
    - name: Change jenkins configuration file
      ansible.builtin.replace:
        path: /var/lib/jenkins/nodes/slave/config.xml
        regexp: '<host>{{oldip}}</host>'
        replace: "<host>{{ hostvars['slave']['ansible_host']}}</host>"
      
    - name: Start Jenkins
      systemd:
        name: jenkins
        state: started
  when: inventory_hostname == "master"