#----------------------------------------------------
#
# Deployment with 3 replicas including livenessProbe and readinessProbe
#
# Deployment with curlpod for checking conteiners in other deployment
#
# Made by Dmytro Liskevych 2021
#
#----------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-project
  namespace: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: myapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myapp
    spec:
      containers:
      - name: myapp
        image: sv301185/k8sphp
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 15
          successThreshold: 1
          failureThreshold: 1
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          successThreshold: 1
          failureThreshold: 1
          periodSeconds: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-pod
  namespace: homework
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: curlpod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: curlpod
    spec:
      containers:
        - name: curlpod
          command:
          - sh
          - -c
          - while true; do sleep 1; done
          image: curlimages/curl
