---
# tasks file for jenkins_slave
- block: # =======Block for SLAVE======
    - name: Add user to remote hosts
      user: name=silver groups=wheel 
 
    - name: Add SSH keys to remote hosts
      authorized_key: user=silver key="{{ lookup('file', "/home/silver/.ssh/id_rsa.pub") }}"
 
    - name: Add user to remote hosts
      user: name=jenkins groups=wheel 
 
    - name: Add SSH keys to remote hosts
      authorized_key: user=jenkins key="{{ lookup('file', "/home/silver/.ssh/id_rsa.pub") }}"
      
    - name: dns
      copy: src=/home/silver/ansible/files/resolv.conf dest=/etc/      
      
              
    - name: Install yum GIT JAVA WGET
      yum:
        name:
          - wget
          - nano
          - java-1.8.0-openjdk
          - git

    - name: Download go.repo
      get_url:
        url: https://mirror.go-repo.io/centos/go-repo.repo
        dest: /etc/yum.repos.d/go-repo.repo

    - name: Import Key
      rpm_key:
        state: present
        key: https://mirror.go-repo.io/centos/RPM-GPG-KEY-GO-REPO

    - name: Install GO
      yum:
        name: golang
        state: present
            
    - name: Copy backup from bcp to slave
      tags: sync-push
      synchronize:
        src: /mnt/sdb/bcp/jslave/{{bcname}}
        dest: /tmp/{{bcname}}
        mode: push
      delegate_to: "{{groups['jenkins'][2]}}"
      register: syncfile            

    - name: Restore Jenkins on Slave Node
      ansible.builtin.unarchive:
        src: /tmp/{{bcname}}
        dest: /
        remote_src: yes
  when: inventory_hostname == "slave"