version: '3'
services:
  app:
    container_name: phabricator
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - phabricator
    ports:
      - 80:80
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${sqlpass}
    volumes:
      - ./data/mysql:/var/lib/mysql:z
#      - ./etc/my.cnf:/etc/mysql/conf.d/my.cnf:z
    networks:
      - phabricator
      
networks:
  phabricator:
    driver: bridge
